mywebsite/Blog/urls.py
# from django.urls import path
# from . import views
# from .views import produk_detail

# urlpatterns = [
#     path('', views.index),
#     path('serializer/', views.produk_detail, name='produk')
# ]
from django.contrib import admin
from django.urls import path,include

from . import views 
from .filters import ProdukFilter
urlpatterns = [
  path('admin/', admin.site.urls),
  path('', views.index,name='index'),
  path('indexstatus', views.indexstatus,name='indexstatus'),
       path('indexsearch', views.product_list, name='index_search'),
  path('indexkategori', views.indexkategori,name='indexkategori'),
  path('produk/', views.produkListCreateView.as_view(), name='produk-list-create'),
  path('status/', views.statusListCreateView.as_view(), name='kategori-list-create'),
  path('kategori/', views.kategoriListCreateView.as_view(), name='kategori-list-create'),
  
  path('produk', views.ProdukListView.as_view(), name='produk-list'),
   
  path('kategori/<int:pk>/', views.kategoriDetailView.as_view(), name='kategori-detail'),
  
  path('create/',views.create,name='create'),
  path('delete/<delete_id>', views.delete, name='delete'),
  path('update/<update_id>', views.update, name='update'),
  path('createstatus/',views.createStatus,name='createstatus'),
  path('deletestatus/<delete_id>',views.deletestatus,name='deletestatus'),
  path('updatestatus/<update_id>', views.updateStatus, name='updatestatus'),
   path('createkategori/',views.createKategori,name='createkategori'),
  path('updatekategori/<update_id>', views.updatekategori, name='updatekategori'),
    path('deletekategori/<delete_id>',views.deletekategori,name='deletekategori'),
    
]

mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.http import HttpResponse


# from . import views
# def index(request):
#     return HttpResponse("halo dunia")
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('Blog.urls')),
    # path('', Blogurls.index),
    # path('blog', blogViews.index),
    # # path('about/', Blogurls.about),
    path('',include('Blog.urls'),name='Blog'),
    # path('Blog2/',include('Blog.urls'),)

    
]

mywebsite/Blog/models.py
from django.db import models

# Create your models here.

class kategori(models.Model):
    id_kategori = models.BigAutoField(auto_created=True,primary_key=True,verbose_name="ID")
    nama_kategori = models.CharField(max_length=100)
    def __str__(self):
        return self.nama_kategori
class status(models.Model):
    id_status = models.BigAutoField(auto_created=True,primary_key=True,verbose_name="ID")
    nama_status = models.CharField(max_length=255)
    def __str__(self):
        return self.nama_status

class produk(models.Model):
    no =models.BigAutoField(auto_created=True,primary_key=True,verbose_name="ID")
    id_produk = models.IntegerField()
    nama_produk = models.CharField(max_length=255)
    status_id = models.ForeignKey(status, on_delete=models.CASCADE)
    harga = models.IntegerField()
    kategori_id = models.ForeignKey(kategori,on_delete=models.CASCADE)
    # def __str__(self):
    #     return self.status_id

mywebsite/Blog/forms.py
from django import forms
from .models import status,produk,kategori

class PostForm(forms.ModelForm):
    class Meta:
        model = produk
        fields=[
            'id_produk',
            'nama_produk',
            'harga',
            'status_id',
            'kategori_id'
        
        ]
        widgets = {
            'id_produk': forms.NumberInput(attrs={'class':'form-control','min': '1', 'max': '10000000'}),
            'nama_produk': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan Nama Produk'
                }
            ), 
            'harga': forms.NumberInput(attrs={ 'class':'form-control','min': '10', 'max': '10000000'}),  
                  'status_id': forms.Select(attrs={'class':'form-control'}),
         'kategori_id': forms.Select(attrs={'class':'form-control'}),
        }
class StatusForm(forms.ModelForm):
    class Meta:
        model = status
        fields=[
          
            'nama_status'
        ]
        widgets = {
               'id_status': forms.NumberInput(attrs={'class':'form-control','min': '1', 'max': '10000000'}),
               'nama_status': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan Nama Status'
                }
            ), 
        }
class KategoriForm(forms.ModelForm):
    class Meta:
        model = kategori
        fields=[
            'nama_kategori',
        ]
        widgets = {
             'id_kategori': forms.NumberInput(attrs={'class':'form-control','min': '1', 'max': '10000000'}),
               'nama_kategori': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan Nama Kategori'
                }
            ), 
        }

class UpdateStatusForm(forms.ModelForm):
    class Meta:
        model = status
        fields=[
            
            'nama_status',
        ]
        widgets= {
                'id_status': forms.NumberInput(attrs={'class':'form-control','min': '1', 'max': '10000000'}),
               'nama_status': forms.Select(attrs={'class':'form-control'}),
        }
class UpdateForm(forms.ModelForm):
    class Meta:
        model = produk
        fields=[
         
            'nama_produk',
            'harga',
            'status_id',
            'kategori_id'
        
        ]
        widgets = {
            
            'nama_produk': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Masukkan Nama Produk'
                }
            ), 
            'harga': forms.NumberInput(attrs={ 'class':'form-control','min': '10', 'max': '10000000'}),  
                  'status_id': forms.Select(attrs={'class':'form-control'}),
         'kategori_id': forms.Select(attrs={'class':'form-control'}),
        }   
    # id_produk = forms.IntegerField()
    # nama_produk = forms.CharField(max_length=255)
    # kategori = forms.ChoiceField(
    #     widget=forms.Select,
    #     choices=produk.STATUS_CHOICES,
        
    # )
    # harga = forms.IntegerField()
    # status = forms.ModelChoiceField(queryset=status.objects.all())
    
    # class ProductSearchForm(forms.Form):
    #     search_query = forms.CharField(
    #         max_length=100,
    #         required=False,
    #         label='Search',
    #         widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Search Products'})
    #     )

mywebsite/Blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
# Create your views here.
from .models import produk,status,kategori
from django.contrib import messages
from .serializers import produkSerializer,kategoriSerializer,statusSerializer

from rest_framework.renderers import JSONRenderer
from .forms import PostForm,StatusForm,KategoriForm
from rest_framework import generics, viewsets, filters
from .filters import ProdukFilter
from django_filters.rest_framework import DjangoFilterBackend
def indexkategori(request):
    kategoris= kategori.objects.all().order_by('pk')
    
    
    
    context ={
        'title':' Apikasi Rekayasa Data Produk Dengan Django & PostgreSQL',
        'Heading' : 'Halaman Kategori',
        'Kategoris':kategoris,
       
    }
    return render(request, 'blog/indexkategori.html',context)

def updatekategori(request,update_id):
    
    akun_update = kategori.objects.get(id_kategori=update_id)
   
    data = {
        'nama_kategori' : akun_update.nama_kategori,
      
        
    }
    akun_form = KategoriForm(request.POST or None, initial=data,instance=akun_update)
    if request.method =='POST':
        if akun_form.is_valid():
         
            akun_form.save()
        return redirect("indexkategori")
    context = {
        'title':'Update Data Status',
        'kategori_form':akun_form
    }

    return render(request, 'blog/createkategori.html',context)

def deletekategori(request,delete_id):
   kategori.objects.filter(id_kategori=delete_id).delete()
   messages.success(request, 'Item has been successfully deleted.')
   return redirect("indexkategori")

def indexstatus(request):
    
    statuss= status.objects.all().order_by('pk')
 
    context ={
        'title':' Apikasi Rekayasa Data Produk Dengan Django & PostgreSQL',
        'Heading' : 'Halaman Status',

        'Statuss':statuss,
    
    }
    return render(request, 'blog/indexstatus.html',context)

def createKategori(request):
    kategori_form = KategoriForm(request.POST or None)
    if request.method =='POST':
        if kategori_form.is_valid():
    
            kategori_form.save()
        return redirect("indexkategori")
    context = {
        'title':'Tambahkan Kategori',
        'kategori_form':kategori_form
    }
    return render(request, 'blog/createkategori.html',context)

def createStatus(request):
    status_form = StatusForm(request.POST or None)
    if request.method =='POST':
        if status_form.is_valid():
    
            status_form.save()
        return redirect("indexstatus")
    context = {
        'title':'Tambahkan Status',
        'status_form':status_form
    }
    return render(request, 'blog/createstatus.html',context)

def updateStatus(request,update_id):
    
    akun_update = status.objects.get(id_status=update_id)
   
    data = {
        'nama_status' : akun_update.nama_status,
      
        
    }
    akun_form = StatusForm(request.POST or None, initial=data,instance=akun_update)
    if request.method =='POST':
        if akun_form.is_valid():
         
            akun_form.save()
        return redirect("indexstatus")
    context = {
        'title':'Update Data Status',
        'status_form':akun_form
    }

    return render(request, 'blog/createstatus.html',context)

def deletestatus(request,delete_id):
   status.objects.filter(id_status=delete_id).delete()
   messages.success(request, 'Item has been successfully deleted.')
   return redirect("indexstatus")

def index(request):
    # produks= produk.objects.all().order_by('pk')
    
    produks = produk.objects.filter(status_id__nama_status="bisa dijual").order_by('pk')
    # print(books_with_authors)
    
    
    context ={
        'title':' Apikasi Rekayasa Data Produk Dengan Django & PostgreSQL',
        'Heading' : 'Halaman Produk',
        'Produks':produks,
        # 'Foreign':books_with_authors
    }
    return render(request, 'blog/index.html',context)

def produk_detail(request):
    prd = produk.objects.get(id_produk=6)
    serializer = produkSerializer(prd)
    json_data = JSONRenderer().render(serializer.data)
    return HttpResponse(json_data, content_type='application/json')

def create(request):
    post_form = PostForm(request.POST or None)
    if request.method =='POST':
        if post_form.is_valid():
    
            post_form.save()
        return redirect("index")
    context = {
        'title':'Tambahkan Produk',
        'post_form':post_form
    }
    return render(request, 'blog/create.html',context)

def delete(request,delete_id):
   produk.objects.filter(no=delete_id).delete()
   messages.success(request, 'Item has been successfully deleted.')
   return redirect("index")


def update(request,update_id):
    akun_update = produk.objects.get(no=update_id)
   
    data = {
        'nama_produk' : akun_update.nama_produk,
        'kategori_id' : akun_update.kategori_id,
        'harga' : akun_update.harga,
        'status_id_id' : akun_update.status_id_id,
        
    }
    akun_form = PostForm(request.POST or None, initial=data,instance=akun_update)
    if request.method =='POST':
        if akun_form.is_valid():
         
            akun_form.save()
        return redirect("index")
    context = {
        'title':'Update Data',
        'post_form':akun_form
    }

    return render(request, 'blog/create.html',context)

class produkListCreateView(generics.ListCreateAPIView):
    queryset = produk.objects.all()
    serializer_class = produkSerializer
        

class ProdukListView(generics.ListAPIView):
    queryset = produk.objects.all()
    serializer_class = produkSerializer
    filterset_class = ProdukFilter
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['id_produk']

class kategoriListCreateView(generics.ListCreateAPIView):
    queryset = kategori.objects.all()
    serializer_class = kategoriSerializer
    
class kategoriDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = kategori.objects.all()
    serializer_class = kategoriSerializer
class statusListCreateView(generics.ListCreateAPIView):
    queryset = status.objects.all()
    serializer_class = statusSerializer
# class statusListCreateView(generics.ListCreateAPIView):
#     queryset = status.objects.all()
#     serializer_class = statusSerializer
# class statusDetailView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = status.objects.all()
#     serializer_class = statusSerializer

def product_list(request):
    products = produk.objects.all().order_by('pk')
    search_query = request.GET.get('search_query', '')
    # print(search_query)
    
    if search_query:
        products = products.filter(nama_produk__icontains=search_query)
        print('masuk')
    return render(request, 'blog/index2.html', {'products': products, 'search_query': search_query})
          

mywebsite/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %} {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="#">Tutorial Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Blog
	        </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                        <a class="dropdown-item" href="{% url 'indexstatus' %}">Status</a>
                        <a class="dropdown-item" href="{% url 'indexkategori' %}">Kategori</a>
                    </div>
                </li>

            </ul>

        </div>

    </nav>
    <div class="container">
        {% block contents %} {% endblock contents %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>

mywebsite/templates/blog.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <p>Selamat Datang</p>
</body>

</html>

mywebsite/templates/bs.html
 {% extends "base.html" %} {% block page_title %} {{page_title}} {% endblock page_title %} {% block contents %}
<h1>{{title}}</h1>
<form method="POST">
    {% csrf_token %}
    <div class="table-responsive-sm">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Id Produk</th>
                    <th scope="col">Nama Produk</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Status</th>
                    <th scope="col">Kategori</th>
                    <th style="text-align:center">Aksi</th>
                </tr>
            </thead>
            <tbody>
                {{post_form.as_table}} {% for produk in Produks %}
                <tr>
                    <td>{{produk.id}}</td>
                    <td>{{produk.id_produk}}</td>
                    <td>{{produk.nama_produk}}</td>
                    <td>{{produk.harga}}</td>
                    <td>{{produk.status_id}}</td>
                    <td>{{produk.get_kategori_id_display}}</td>
                    <td>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
    Delete 
  </button>

                        <a class="btn btn-warning" href="{% url 'update' produk.id %}" title="">Update</a>
                    </td>
                </tr>

                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
                            </div>
                            <div class="modal-body">
                                Apakah Ingin Menghapus {{produk.nama_produk}}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <a href="{% url 'delete' produk.id %}" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

        </table>
        <a class="btn btn-primary" href="{% url 'create' %}">Tambah</a>
    </div>

</form>
{% endblock contents %}

mywebsite/templates/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APLIKASI PENAMBAHAN PRODUK DENGAN DJANGO</title>
</head>

<body>
    <h1>Selamat datang di Aplikasi Penambahana Produk Dengan Django</h1>

    <ul>
        <li><a href="about" title="">about</a></li>
        <li><a href="Blog/index.html" title="">blog</a></li>
    </ul>
</body>

</html>

mywebsite/templates/index.html
{% extends "base.html" %} {% block title %} {{title}} {% endblock page_title %} {% block contents %}
<h1>{{title}}</h1>
{% endblock contents %}